#!/bin/bash
# DIFY_API_KEY修正ガイド

PROJECT_ID="aikaapp-584fa"

echo "🔧 DIFY_API_KEY修正手順"
echo ""
echo "現在のSecret Managerの値に全角文字が含まれている可能性があります。"
echo ""
echo "📋 修正手順:"
echo ""
echo "1. Google Cloud ConsoleでSecret Managerを開く:"
echo "   https://console.cloud.google.com/security/secret-manager/secret/DIFY_API_KEY?project=$PROJECT_ID"
echo ""
echo "2. 「新しいバージョン」をクリック"
echo ""
echo "3. 正しいAPIキーを入力（重要）:"
echo "   - ASCII文字のみ（英数字、記号）"
echo "   - 末尾改行・空白・全角・不可視文字ゼロ"
echo "   - 通常は app- で始まる文字列"
echo ""
echo "4. 「バージョンを作成」をクリック"
echo ""
echo "5. 新バージョンを選択し、「エイリアスを追加」→ エイリアス名: prod"
echo "   または既存のprodエイリアスを新バージョンに更新"
echo ""
echo "6. 確認（新バージョン番号を確認）:"
echo "   gcloud secrets versions list DIFY_API_KEY --project=$PROJECT_ID --format='table(name,state,createTime,aliases)' --limit=5"
echo ""
echo "7. Cloud Runを再デプロイ:"
echo "   ./deploy.sh"
echo ""
echo "8. ログを確認:"
echo "   ./check_auth_status.sh"
